* Meeting summary

** Mar 27
*** Discussion Points
- When implement MSCLE, I find that 'nnet:multinom' may not use the offset term
   as we want. I will try to figure it out and write getMSLE by hand as a
   comparison.


** Mar 20
*** Discussion Points*** Points
- Fix (n.plt+n.ssp) and then enlarge n.plt so that \(Var(\hat{\beta}_{cmb} -
   \beta_{true})\) should be close to \(Var(\hat{\beta}_{plt} - \beta_{true})\)
   . The simulation results show that it meets expectation except when n.plt
    and n.ssp are both large. Try to use degree of freedom to correct.

- Implement MSCLE. First implement OptL.

** Mar 6
*** Discussion Points
- Since \(Var(\hat{\beta}_{plt} - \beta_{true})\) and \(Var(\hat{\beta}_{ssp}
  - \beta_{true})\) work well, we should double check the calculation of
    \(Var(\hat{\beta}_{cmb} - \beta_{true})\). Simulation strategy: fix
    (n.plt+n.ssp) and then enlarge n.plt so that \(Var(\hat{\beta}_{cmb} -
     \beta_{true})\) should be close to \(Var(\hat{\beta}_{plt} -
      \beta_{true})\).

** Feb 21
*** Discussion Points
- When calculating \(Var(\hat{\beta}_{plt} - \beta_{true})\), I forgot to add a
   term to correct its difference with \(Var(\hat{\beta}_{plt} -
   \beta_{full})\). As a result, this term is missed in the calculation of
    \(Var(\hat{\beta}_{cmb} - \beta_{true})\). Check this problem in softmax
     code and previous code.

- Implement MSCLE with the assistance of the Julia code. First implement OptL.

- LUC
