# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

softmax_dL_sq_cpp <- function(X, Y_matrix, P, p, K, d, scale) {
    .Call('_subsampling_softmax_dL_sq_cpp', PACKAGE = 'subsampling', X, Y_matrix, P, p, K, d, scale)
}

softmax_ddL_cpp <- function(X, P, p, K, d, scale) {
    .Call('_subsampling_softmax_ddL_cpp', PACKAGE = 'subsampling', X, P, p, K, d, scale)
}

softmax_Omega_cpp <- function(X, P1, p, K, d, scale) {
    .Call('_subsampling_softmax_Omega_cpp', PACKAGE = 'subsampling', X, P1, p, K, d, scale)
}

